---
  - name: Create minIO directories for minIO server
    file:
      path: "{{ item }}"
      state: directory
      mode: 0775
    loop:
      - /minio/data
      - /minio/config
  - name: Create MinIO container
    become: yes
    containers.podman.podman_container:
      name: minio
      image: minio/minio
      state: started
      recreate: yes
      ports:
        - 9000:9000
      volumes:
        -  /minio/config:/root/.minio:z
        -  /minio/data:/data:z
      env:
        MINIO_ACCESS_KEY: "MINIOKEYMINIO"
        MINIO_SECRET_KEY: "MINIOSECRETKEYMINIO"
      command: server /data
