---
  - name: Creo las credenciales para velero
    shell:
      cmd: |
       cat << EOF > credentials-velero
       [default]
       aws_access_key_id = MINIOKEYMINIO
       aws_secret_access_key = MINIOSECRETKEYMINIO
       EOF
  - name: Velero install in OCP
    shell:
      cmd: |
       velero install \
           --provider aws \
           --plugins velero/velero-plugin-for-aws:v1.0.0 \
           --bucket velero \
           --secret-file ./credentials-velero \
           --use-volume-snapshots=false \
           --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://${HOSTNAME}:9000
       	  
